Repository wooahan-agile/idu-market-react-native, pull requests merged in 2021-04, with the labels that each got.

#8 [market] 장터 UI 구현 완료
  app/assets/images/1917.jpg
  app/assets/images/her.jpg
  app/assets/images/극한직업.jpg
  app/assets/images/어벤져스.jpg
  app/package-lock.json
  app/package.json
  app/src/constants/image.js
  app/src/constants/index.js
  app/src/screens/Markets.js
  app/src/theme.js
Labels: 리액트 네이티브, 스타일링

#10 [login] 로그인 서버 연동
  app/package.json
  app/src/navigations/AuthStack.js
  app/src/navigations/index.js
  app/src/screens/Login.js
  app/src/utils/firebase.js
  app/yarn.lock
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 서버

#11 [main] 메인화면 UI 초기설계 구현
  app/src/contexts/User.js
  app/src/screens/Main.js
  app/src/screens/idu2.jpg
Labels: 기획 및 설계, 리액트 네이티브, 스타일링

#14 [board] 게시판 상세, 글쓰기 UI #6
  app/App.js
  app/assets/images/1917.jpg
  app/assets/images/her.jpg
  app/assets/images/극한직업.jpg
  app/assets/images/어벤져스.jpg
  app/firebase.json
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/components/Btn.js
  app/src/components/Button.js
  app/src/components/Input.js
  app/src/components/Spinner.js
  app/src/components/index.js
  app/src/constants/image.js
  app/src/constants/index.js
  app/src/contexts/Progress.js
  app/src/contexts/User.js
  app/src/contexts/index.js
  app/src/navigations/AuthStack.js
  app/src/navigations/MainStack.js
  app/src/navigations/MainTab.js
  app/src/navigations/index.js
  app/src/screens/Boards.js
  app/src/screens/FindId.js
  app/src/screens/FindPw.js
  app/src/screens/Login.js
  app/src/screens/Main.js
  app/src/screens/Markets.js
  app/src/screens/NoticeBoard.js
  app/src/screens/Profile.js
  app/src/screens/Signup.js
  app/src/screens/index.js
  app/src/theme.js
  app/src/utils/common.js
  app/src/utils/firebase.js
  app/yarn.lock
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 서버, 스타일링

#16 fix(sangjun/board): 게시판상세, 글쓰기UI #6
  app/package-lock.json
  app/package.json
  app/src/navigations/MainStack.js
  app/src/navigations/MainTab.js
  app/src/screens/Boards.js
  app/src/screens/FreeBoard.js
  app/src/screens/PostWrite.js
  app/src/screens/ViewDetail.js
  app/src/screens/index.js
  app/src/theme.js
Labels: 기획 및 설계, 리액트 네이티브, 스타일링

#17 [login] 로그인 서버 연동
  app/src/contexts/User.js
  app/src/navigations/index.js
  app/src/screens/Login.js
  app/src/theme.js
  app/src/utils/AsyncStorage.js
Labels: 기능구현, 리액트 네이티브

#20 [signup] 회원가입 UI 구현 & 서버와 연동
  app/src/components/Input.js
  app/src/screens/Signup.js
  app/src/theme.js
Labels: 기능구현, 리액트 네이티브, 서버, 스타일링

#21 [login] 로그인 UI 수정
  app/src/screens/Login.js
Labels: 리액트 네이티브, 스타일링
