Repository wooahan-agile/idu-market-react-native, pull requests merged in 2021-05, with the labels that each got.

#23 [signup] 회원가입 UI 구현
  app/src/components/Input.js
  app/src/screens/Signup.js
Labels: 리액트 네이티브, 스타일링

#24 Add(sangjun/board): 사진첩접근 한장업로드, 로그인 화면이동#18
  app/package-lock.json
  app/package.json
  app/src/components/Button.js
  app/src/components/Image.js
  app/src/components/index.js
  app/src/navigations/MainStack.js
  app/src/navigations/MainTab.js
  app/src/navigations/index.js
  app/src/screens/Login.js
  app/src/screens/PostWrite.js
  app/src/screens/Profile.js
  app/src/theme.js
  app/src/utils/images.js
  app/yarn.lock
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#25 [main] 메인 화면 UI 및 기능 구현
  app/src/components/Main/Topic.js
  app/src/components/Main/linear/Item.js
  app/src/components/Main/linear/ItemList.js
  app/src/components/Main/linear/LinearContainer.js
  app/src/components/Main/market/Item.js
  app/src/components/Main/market/ItemList.js
  app/src/components/Main/market/MarketContainer.js
  app/src/screens/Main.js
Labels: 기능구현, 리액트 네이티브, 서버, 스타일링

#27 [boards] 마켓 게시판 List UI 구현
  app/package-lock.json
  app/src/screens/Main.js
  app/src/screens/Markets.js
Labels: 기획 및 설계, 리액트 네이티브, 스타일링

#30 [boards] 마켓 게시판 List UI 및 기능 구현
  app/assets/images/1917.jpg
  app/assets/images/her.jpg
  app/assets/images/극한직업.jpg
  app/assets/images/어벤져스.jpg
  app/src/components/Markets/Item.js
  app/src/constants/image.js
  app/src/constants/index.js
  app/src/screens/Main.js
  app/src/screens/Markets.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브

#32 [profile] 프로필 UI 구현 #28
  app/package.json
  app/src/components/Boards/FreeBoardComponent.js
  app/src/components/FindButton.js
  app/src/components/Profile/ProfileComponent.js
  app/src/components/index.js
  app/src/navigations/MainStack.js
  app/src/navigations/MainTab.js
  app/src/screens/ViewDetail.js
  app/src/screens/auth/Login.js
  app/src/screens/auth/Signup.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/profiles/Profile.js
  app/src/theme.js
  app/yarn.lock
Labels: 기획 및 설계, 리액트 네이티브, 스타일링

#33 [boards] 상세화면 UI 구현 완료
  app/package-lock.json
  app/package.json
  app/src/components/boards/read-detail/ImageSliderContainer.js
  app/src/components/boards/read-detail/PostContainer.js
  app/src/components/boards/read-detail/comments/CommentContainer.js
  app/src/components/boards/read-detail/posts/Post.js
  app/src/components/mains/linear/ItemList.js
  app/src/navigations/MainStack.js
  app/src/navigations/MainTab.js
  app/src/screens/Main.js
  app/src/screens/ViewDetail.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/boards/read-detail/ViewDetail.js
  app/src/screens/index.js
  app/src/theme.js
Labels: 기획 및 설계, 리액트 네이티브, 스타일링

#34 [Docs] components 안 폴더명 변경
  app/src/components/boards/FreeBoardComponent.js
  app/src/components/boards/read-detail/PostContainer.js
  app/src/components/markets/Item.js
  app/src/components/profiles/ProfileComponent.js
  app/src/navigations/MainStack.js
  app/src/screens/Main.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/index.js
Labels: 기획 및 설계, 리액트 네이티브

#38 [signup] 회원가입 폴더 정리 및 전공 분해
  app/package.json
  app/src/components/FindButton.js
  app/src/components/buttons/Button.js
  app/src/components/buttons/FindButton.js
  app/src/components/index.js
  app/src/screens/auth/Login.js
  app/src/screens/auth/Signup.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/utils/majors.js
  app/yarn.lock
Labels: 리액트 네이티브, 스타일링

#39 [profile] 프로필 수정 구현 #36
  app/src/components/auth/FindId.js
  app/src/components/auth/FindPw.js
  app/src/components/profiles/ProfileInfo.js
  app/src/components/profiles/ProfileInfomationContainer.js
  app/src/components/profiles/ProfileUpdateInfo.js
  app/src/components/profiles/Watchlist.js
  app/src/navigations/MainStack.js
  app/src/navigations/index.js
  app/src/screens/auth/Find.js
  app/src/screens/auth/FindId.js
  app/src/screens/auth/FindPw.js
  app/src/screens/index.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/ProfileUpdate.js
Labels: 기능구현, 리액트 네이티브, 스타일링

#42 [find] 아이디, 비밀번호 찾기 기능 #40
  app/src/components/auth/FindId.js
  app/src/components/auth/FindPw.js
  app/src/components/markets/Item.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/auth/Find.js
  app/src/screens/auth/Login.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/ProfileUpdate.js
  app/src/screens/profiles/PurchaseList.js
  app/src/screens/profiles/SaleList.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#43 [profile] 프로필 수정시 수정내용 바로적용, 학과를 선택해야만 프로필 수정 가능
  app/package.json
  app/src/components/auth/FindId.js
  app/src/components/auth/FindPw.js
  app/src/components/mains/linear/ItemList.js
  app/src/components/mains/market/ItemList.js
  app/src/components/profiles/ProfileInfo.js
  app/src/components/profiles/ProfileUpdateInfo.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/auth/Find.js
  app/src/screens/auth/Login.js
  app/src/screens/auth/Signup.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/ProfileUpdate.js
  app/src/screens/profiles/PurchaseList.js
  app/src/screens/profiles/SaleList.js
  app/yarn.lock
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#45 fix(sangjun/fetch): API headers 수정
  app/src/components/mains/linear/ItemList.js
  app/src/components/mains/market/ItemList.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/ProfileUpdate.js
  app/src/screens/profiles/PurchaseList.js
  app/src/screens/profiles/SaleList.js
Labels: 리액트 네이티브, 서버

#47 [inquiry] 문의사항 UI, 기능 구현
  app/src/screens/profiles/Inquiry.js
  app/src/screens/profiles/ProfileUpdate.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#49 [detailView] : detailView API 값 불러오기
  app/src/components/boards/FreeBoardComponent.js
  app/src/components/boards/Item.js
  app/src/components/boards/read-detail/PostContainer.js
  app/src/components/boards/read-detail/comments/CommentContainer.js
  app/src/components/boards/read-detail/comments/Item.js
  app/src/components/boards/read-detail/posts/Post.js
  app/src/components/markets/Item.js
  app/src/components/profiles/ActionButtonContainer.js
  app/src/components/profiles/ProfileInfomationContainer.js
  app/src/components/profiles/ProfileUpdateInfo.js
  app/src/navigations/MainStack.js
  app/src/screens/Main.js
  app/src/screens/auth/Login.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/index.js
  app/src/screens/profiles/ProfileUpdate.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#51 [watchlist]관심목록 등록,취소 기능 구현
  app/src/components/boards/read-detail/PostContainer.js
  app/src/components/boards/read-detail/comments/Item.js
  app/src/components/boards/read-detail/posts/Post.js
  app/src/components/markets/Item.js
  app/src/components/profiles/ActionButtonContainer.js
  app/src/components/profiles/ProfileUpdateInfo.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/PurchaseList.js
  app/src/screens/profiles/SaleList.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#53 [hit] 조회수 기능 추가 #41
  app/src/components/boards/FreeBoardComponent.js
  app/src/components/mains/linear/Item.js
  app/src/components/mains/linear/ItemList.js
  app/src/components/mains/market/Item.js
  app/src/components/mains/market/ItemList.js
  app/src/components/markets/Item.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/boards/read-all/FreeBoard.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/profiles/Profile.js
Labels: 기능구현, 기획 및 설계, 리액트 네이티브, 스타일링

#56 [webView] 정규식 변경 #54
  app/package-lock.json
  app/package.json
  app/src/components/boards/read-detail/posts/Post.js
  app/src/components/markets/Item.js
  app/src/components/profiles/ProfileInfomationContainer.js
  app/src/components/profiles/Watchlist.js
  app/src/screens/Main.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/screens/profiles/Profile.js
  app/src/screens/profiles/SaleList.js
  app/yarn-error.log
  app/yarn.lock
Labels: 리액트 네이티브, 스타일링

#57 Fix(sangjun/main): 게시글 정보변경 즉시적용, 작성자 표시 id에서 닉네임으로 변경 #55
  app/src/components/mains/linear/Item.js
  app/src/components/mains/linear/ItemList.js
  app/src/components/mains/market/Item.js
  app/src/components/mains/market/ItemList.js
  app/src/screens/Main.js
  app/src/screens/boards/read-all/Market.js
Labels: 기능구현, 리액트 네이티브, 스타일링

#60 [detailView] 게시글 작성자 수정,삭제 버튼 #58
  app/firebase.json
  app/src/components/auth/FindPw.js
  app/src/components/boards/read-detail/posts/Post.js
  app/src/components/mains/market/ItemList.js
  app/src/screens/auth/Login.js
  app/src/screens/auth/Signup.js
  app/src/screens/boards/read-all/Market.js
  app/src/screens/boards/read-detail/DetailView.js
  app/src/utils/common.js
Labels: 기능구현, 리액트 네이티브, 스타일링
